env:
  TERM: screen-256color
window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 20
    y: 15
  dynamic_padding: true
  decorations: buttonless
  startup_mode: Windowed
scrolling:
  history: 10000
  multiplier: 3
  faux_multiplier: 3
  auto_scroll: false
font:
  normal:
    family: DankMono Nerd Font Mono
    style: Regular
  bold:
    family: DankMono Nerd Font Mono
    style: auto
  italic:
    family: DankMono Nerd Font Mono
    style: auto
  bold_italic:
    family: DankMono Nerd Font Mono
    style: auto
  size: 19.0
  offset:
    x: 0
    y: 1
  glyph_offset:
    x: 0
    y: 1
  use_thin_strokes: true

# Colors (Doom One)
# colors:
#   primary:
#     background: '0x282a36'
#     foreground: '0xeff0eb'
#   normal:
#     black:   '0x686868'
#     red:     '0xFF5C57'
#     green:   '0x5AF78E'
#     yellow:  '0xF3F99D'
#     blue:    '0x57C7FF'
#     magenta: '0xFF6AC1'
#     cyan:    '0x9AEDFE'
#     white:   '0xF1F1F0'
# TokyoNight Alacritty Colors
# colors:
#   # Default colors
#   primary:
#     background: '0x24283b'
#     foreground: '0xc0caf5'

#   # Normal colors
#   normal:
#     black:   '0x1D202F'
#     red:     '0xf7768e'
#     green:   '0x9ece6a'
#     yellow:  '0xe0af68'
#     blue:    '0x7aa2f7'
#     magenta: '0xbb9af7'
#     cyan:    '0x7dcfff'
#     white:   '0xa9b1d6'

#   # Bright colors
#   bright:
#     black:   '0x414868'
#     red:     '0xf7768e'
#     green:   '0x9ece6a'
#     yellow:  '0xe0af68'
#     blue:    '0x7aa2f7'
#     magenta: '0xbb9af7'
#     cyan:    '0x7dcfff'
#     white:   '0xc0caf5'

#   indexed_colors:
#     - { index: 16, color: '0xff9e64' }
#     - { index: 17, color: '0xdb4b4b' }
# github Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x24292e'
    foreground: '0xd1d5da'

  # Normal colors
  normal:
    black:   '0x24292e'
    red:     '0xf14c4c'
    green:   '0x23d18b'
    yellow:  '0xe2e210'
    blue:    '0x3b8eea'
    magenta: '0xbc3fbc'
    cyan:    '0x29b7da'
    white:   '0xd1d5da'

  # Bright colors
  bright:
    black:   '0x666666'
    red:     '0xf14c4c'
    green:   '0x23d18b'
    yellow:  '0xf5f543'
    blue:    '0x3b8eea'
    magenta: '0xd670d6'
    cyan:    '0x29b7da'
    white:   '0xd1d5da'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xf14c4c' }

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true
cursor:
  style: Block
live_config_reload: true
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - -i
    - "tmux attach 2>/dev/null || tmux"
mouse:
  hide_when_typing: true
key_bindings:
  - { key: Return, mods: Command, action: ToggleSimpleFullscreen }
  - { key: D, mods: Command, chars: "\x01\x76" }
  - { key: D, mods: Command|Shift, chars: "\x01\x73" }
  - { key: W, mods: Command, chars: "\x01\x78" }
  - { key: H, mods: Command, chars: "\x01\x68" }
  - { key: J, mods: Command, chars: "\x01\x6a" }
  - { key: K, mods: Command, chars: "\x01\x6b" }
  - { key: L, mods: Command, chars: "\x01\x6c" }
  - { key: T, mods: Command, chars: "\x01\x63" }
  - { key: RBracket, mods: Command|Shift, chars: "\x01\x6e" }
  - { key: LBracket, mods: Command|Shift, chars: "\x01\x70" }
  - { key: Return, mods: Command|Shift, chars: "\x01\x7a" }
  - { key: Key1, mods: Command, chars: "\x01\x31" }
  - { key: Key2, mods: Command, chars: "\x01\x32" }
  - { key: Key3, mods: Command, chars: "\x01\x33" }
  - { key: Key4, mods: Command, chars: "\x01\x34" }
  - { key: Key5, mods: Command, chars: "\x01\x35" }
  - { key: Key6, mods: Command, chars: "\x01\x36" }
  - { key: Key7, mods: Command, chars: "\x01\x37" }
  - { key: Key8, mods: Command, chars: "\x01\x38" }
  - { key: Key9, mods: Command, chars: "\x01\x39" }
  - { key: Left, mods: Command, chars: "\x01\x48" }
  - { key: Down, mods: Command, chars: "\x01\x4a" }
  - { key: Up, mods: Command, chars: "\x01\x4b" }
  - { key: Right, mods: Command, chars: "\x01\x4c" }
